[package]
name = "rslam-dataset-reader"
edition.workspace = true
license.workspace = true
readme.workspace = true
version.workspace = true

[dependencies]
csv = "1.3.1"
rslam-core.workspace = true
rslam-sensor.workspace = true
sophus.workspace = true
opencv.workspace = true
log.workspace = true
